USEMODULE += psa_cc
USEMODULE += psa_cc_error_conversion

ifneq (,$(filter psa_cc_hashes_sha1,$(USEMODULE)))
  USEMODULE += psa_cc_hashes_common
endif

ifneq (,$(filter psa_cc_hashes_sha224,$(USEMODULE)))
  USEMODULE += psa_cc_hashes_common
endif

ifneq (,$(filter psa_cc_hashes_sha256,$(USEMODULE)))
  USEMODULE += psa_cc_hashes_common
endif

ifneq (,$(filter psa_cc_hashes_sha512,$(USEMODULE)))
  USEMODULE += psa_cc_hashes_common
endif

ifneq (,$(filter psa_cc_aes_cbc,$(USEMODULE)))
  USEMODULE += psa_cc_aes_common
endif

ifneq (,$(filter psa_cc_ecc_p192,$(USEMODULE)))
  USEMODULE += psa_cc_ecc_common
endif

ifneq (,$(filter psa_cc_ecc_p256,$(USEMODULE)))
  USEMODULE += psa_cc_ecc_common
endif
