MODULE := az_riot_pnp_iface

RIOTBASE ?=$(CURDIR)/../../..

# USEMODULE += gnrc_wolfssl_tls
# USEPKG += paho-mqtt 

# #TLS_PORT=1234



# INCLUDES += -I$(RIOTBASE)/modules/mqtts/include

# DIRS += $(RIOTBASE)/modules/mqtts

#CFLAGS +=  -DTLS_PORT='$(TLS_PORT)'

#SRCFILES += tls_api.c
#SRC := mqtts_riot_iface.c 

include $(RIOTBASE)/Makefile.base
