# ifneq (,$(filter mqtts_riot_iface,$(USEMODULE)))
#   USEMODULE_INCLUDES += $(RIOTBASE)/modules/mqtts_riot_iface
# endif

INCLUDES += -I$(RIOTBASE)/modules/mqtts_riot_iface
DIRS += $(RIOTBASE)/modules/mqtts_riot_iface
